steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.prod', '-t', 'us-central1-docker.pkg.dev/project-dep23/repo-dep-prediccion-datapath/image-v11-dep-prediccion-datapath:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/project-dep23/repo-dep-prediccion-datapath/image-v11-dep-prediccion-datapath:latest']