FROM python:3.12-slim

ENV PYTHONUNBUFFERED True

# set the working directory
WORKDIR /usr/src/app

# install dependencies
COPY ./requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

# copy src code
COPY ./src ./src

# copy the model file from src
COPY ./src/precio_casas_pipeline.joblib ./

EXPOSE 4001

# start the server
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "4001", "--proxy-headers"]